from foo import Gene, PairwiseGeneToGeneInteraction
from bar import inject_files, inject_translation_tables, resolve_term

_ingest_code = 'protein-links-detailed'

file, entrez_2_string = inject_files(_ingest_code)
global_translation, local_translation = inject_translation_tables(_ingest_code)

gene_a = Gene
gene_b = Gene

pairwise_gene_to_gene_interaction = PairwiseGeneToGeneInteraction

#################################
# Above would be autogenerated using yaml + codegen
#
# Below contains ingest logic
#################################

gene_a.id = 'NCBIGene:' + entrez_2_string[file['protein1']]['entrez']
gene_b.id = 'NCBIGene:' + entrez_2_string[file['protein2']]['entrez']

pairwise_gene_to_gene_interaction.subject = gene_a
pairwise_gene_to_gene_interaction.object = gene_b
pairwise_gene_to_gene_interaction.relation = global_translation['interacts with']
