from bioweave.model import Gene, PairwiseGeneToGeneInteraction, predicate
from bioweave.facade.data_provider import inject_files, inject_translation_table
from bioweave.facade.data_collector import collect
from bioweave.facade.helper import next_row

_ingest_name = 'protein-links-detailed'

file, entrez_2_string, = inject_files(_ingest_name)
translation_table = inject_translation_table(_ingest_name)

gene_a = Gene()  # Maps to file['protein1']
gene_b = Gene()  # Maps to file['protein2']

pairwise_gene_to_gene_interaction = PairwiseGeneToGeneInteraction(provided_by='stringdb')

model = (gene_a, gene_b, pairwise_gene_to_gene_interaction)

if file['combined_score'] >= 700:
    next_row()

#################################
# Above is autogenerated
#################################




collect(_ingest_name, *model)
