name: Build and Deploy Docs to GitHub Pages
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3
        uses: actions/setup-python@main
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@main

      - name: Install Dependencies
        run: poetry install

      - name: Build Documentation
        run: make docs

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          target-folder: docs
          clean: true
          