name: Build and Deploy Docs to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UV_VERSION: "0.7.x"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3
        uses: actions/setup-python@main
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Verify lockfile is up-to-date
        run: |
          uv lock --check

      - name: Install library
        run: |
          uv sync --extra dev

      - name: Build Documentation
        run: make docs

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          target-folder: docs
          clean: true
          
